apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-url-checker.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ include "prometheus-url-checker.name" . }}
