apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-url-checker.fullname" . }}
  labels:
    app: {{ include "prometheus-url-checker.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "prometheus-url-checker.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "prometheus-url-checker.name" . }}
    spec:
      containers:
      - name: prometheus-url-checker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
